### ISSUE TITLE
Add a period after the number in results numbering

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#100]
Simply adding a . following number in the list of records displayed 

1.   5978       1598          Shakespeare, WIlliam
2.

The period after the 1, 2, 3, 4, etc

**Comment by apjanco** [comment]
The result numbers are added in main/assets/js/deep.js on line [1820](https://github.com/upenndigitalscholarship/deep/blob/fbef5d80b8c45c09ce77a01fefca04ea4e10c5b3/main/assets/js/deep.js#L1820).

**Comment by ZacharyLesser** [comment]
This should probably be fixed in conjunction with #101
