### ISSUE TITLE
get changes from backup database 

### ISSUE THREAD

**Issue by apjanco** [upenndigitalscholarship/deep#104]

**Comment by apjanco** [comment]
-  2 The Troublesome Reign of King John 1591 (5021.02) - 102a [{"changed": {"fields": ["Title Page: Performance", "Independent playbook link"]}}]
-  Cleopatra, Queen of Egypt 1639 (5158.01) - 553a(ii) [{"changed": {"fields": ["Independent playbook link"]}}]
-  Julia Agrippina, Empress of Rome 1639 (5158.02) - 554a(ii) [{"changed": {"fields": ["Independent playbook link"]}}]
-  The Entertainment at Elvetham 1591 (132) - 98a [{"changed": {"fields": ["Greg #(i.e., Greg full, e.g., 197b(*) and 197b(\u2020) for the two issues of the second edition of Hamlet)", "Title Page: Title"]}}]
-  Vertumnus sive Annus Recurrens 1607 (1190) - L6a [{"changed": {"fields": ["Paratext: Dedication", "Variants"]}}]
-  The Entertainment on Michaelmas Day 1613 (The Running Stream Entertainment) (The New River Entertainment) 1613 (5072.02) - 312a [{"changed": {"fields": ["Independent playbook link"]}}]
-  The Lover's Melancholy 1629 (5149.01) - 420a(*) []
-  The Lover's Melancholy 1629 (5149.01) - 420a(*) [{"changed": {"fields": ["Independent playbook link"]}}]
-  The Bloody Brother (Rollo, Duke of Normandy) - 565a - 1 [{"changed": {"fields": ["Authors"]}}]

**Comment by apjanco** [comment]
@ZacharyLesser when you can, please check the comment above. If that's the right data, we can close this issue.

**Comment by ZacharyLesser** [comment]
Thanks, some of these look like dummy entries -- maybe I was testing something or maybe I didn't really change anything in that field but just deleted a space or something. I've re-changed the rest of them.
