### ISSUE TITLE
Item, Edition, Work instead of Item, Edition, Title

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#106]
Just changing the admin descriptor for this level from Titles to Works. No changes to any of the data field names.

**Comment by ZacharyLesser** [comment]
Please also change "Title" to "Work" in the radio button that changes the "views" of results on the site itself (next to "Edition" and "Record")

**Comment by apjanco** [comment]
The Title object in models.py could be renamed to Work. You'll just need to walk down the build pipeline to see what new errors are thrown.  I recommend just changing what's visible to users.  You could change the display in models.py with [Meta](https://stackoverflow.com/questions/8368937/change-model-class-name-in-django-admin-interface). There's a [checkbox in index.html](https://github.com/upenndigitalscholarship/deep/blob/fbef5d80b8c45c09ce77a01fefca04ea4e10c5b3/main/templates/index.html#L76) that could be renamed. I'd be careful about making changes in deep.js.  Good luck! Feel free to write if you run into trouble with this one: apjanco@upenn.edu

**Comment by ZacharyLesser** [comment]
If it's liable to cause errors elsewhere, we could just rename the radio button in the UI without renaming anything in admin
