### ISSUE TITLE
Copy Title and Title Alternative Keywords to Edition Level (leave in place at Title level)

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#117]
We need a copy of these fields and all their data at the Edition Level.

Copy "Title" and put it at Edition level with name "Edition Title"

Copy "Title Alternative Keywords" and put it at Edition level with name "Edition Title Alternative Keywords"

**Comment by ZacharyLesser** [comment]
(This will become important for the Title level View vs Edition level View -- in a few cases, the title of the Work changes in different Editions of that Work...)

**Comment by apjanco** [comment]
I added an edition_title field to Edition.  I copied edition.title.title to each edition.edition_title
