### ISSUE TITLE
Ordering of filter choices for Format

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#136]
They should be listed in this order:

Broadsheet
Folio
Quarto
Octavo
Duodecimo
Sixteenmo

**Comment by apjanco** [comment]
These choices are fetched from formats.json which is generated during build [here](https://github.com/upenndigitalscholarship/deep/blob/fbef5d80b8c45c09ce77a01fefca04ea4e10c5b3/main/management/commands/build.py#L260). If you just reorder things in the json file it will change what's displayed in the dropdown.

**Comment by ZacharyLesser** [comment]
I'm not sure how to do this because the items are not actually listed there...
