### ISSUE TITLE
Filter choice list for Author (Modern) wrongly includes a lot of Stationers

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#139]
This list of filter choices should include only those People-objects that appear in the Authors field in db. Right now, I think it includes every object in the People table?

**Comment by apjanco** [comment]
In build Author is using Person, change to just use the People that appear in Item author
https://github.com/upenndigitalscholarship/deep/blob/5a20b11f23f835f125b0e67e7a4207d0aae400c8/main/management/commands/build.py#L50
