### ISSUE TITLE
Old site collection names also included the year of publication, need to update templates

### ISSUE THREAD

**Issue by apjanco** [upenndigitalscholarship/deep#14]
AssertionError: [*] Error in collection, old: Comedies, Tragicomedies, With other Poems (1651), new: Comedies, Tragicomedies, With other Poems

**Comment by ZacharyLesser** [comment]
Maybe I'm misunderstanding this, but the old site did *not* include year of publication as part of the title of collections. 

see

http://deep.sas.upenn.edu/viewrecord.php?deep_id=5146

(Probably I've misunderstood what you're saying here, but just in case...)
