### ISSUE TITLE
Not working: Play Type = Professional/Nonprofessional

### ISSUE THREAD

**Issue by abfarmer109** [upenndigitalscholarship/deep#148]
Searching/filtering for "Professional" and "Nonprofessional" in "Play Type" is not working.
"Play Type = Professional" results in 1,483 records, many of which are not professional plays.
"Play Type = Nonprofessional" also results in 1,483 records, many of which are not nonprofessional play.

Other specific play types in this search/filter all appear to be correct.

**Comment by ZacharyLesser** [comment]
At the edition level in the field Play Type: Filter, some records will have "Professional" or "Nonprofessional" as one of the terms. This term is generally accompanied by other terms.

The play type = professional should return all records with "professional" as one of the terms in that field.

Play type=nonprofessional returns all records with "nonprofessional" as one of the terms in that field

**Comment by ZacharyLesser** [comment]
I am guessing this is the same problem as in #170 --because the code is looking for character strings rather than discrete tags, it is picking up "Professional" while looking for "Nonprofessional" (or vice versa)
