### ISSUE TITLE
Items with DEEP #s ending in xxxx.10 or .20 or .30 do not build their own page

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#149]
These records therefore cannot be expanded and the specific URL does not exist. This must be because during Build the pages are not created because these decimal numbers are being reduced to xxxx.1 or .2 or .3

We need the code to treat 5081.1 as a distinct number from 5081.10, and so on

**Comment by apjanco** [comment]
I am not able to replicate this error
see:
- https://deep.pennds.org/5081.10/
- https://deep.pennds.org/5143.30

**Comment by ZacharyLesser** [comment]
Try a search for Title = as you like it, and then try to expand the records. They don't expand. But I see that your link is working to 5081.10 so the individual page is working. But why is it not able to expand the view in the Search Results?

**Comment by apjanco** [comment]
issue with expand and 5081.10
let data = item_data[deep_id];

**Comment by apjanco** [comment]
Should be fixed now
