### ISSUE TITLE
Checkboxes for Record Type should act as filters

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#152]
If you go to the home page, do nothing else (no filter term selection at all), but uncheck one of the boxes for Record Type, it should filter to only those items that fit the remaining criteria. The checkboxes should work like filters even if no filter is selected from the drop-down, in other words.

(Right now, all records display if you do this.)

**Comment by apjanco** [comment]
trigger search on change of checkbox

**Comment by ZacharyLesser** [comment]
Initial state upon coming to the website should be to display all records.

Then the checkboxes should function just as the radio buttons do.

Even if no filter is done (e.g. nothing is put in the Title field to start), they should update the results.

**Comment by ZacharyLesser** [comment]
I think this is still not quite working? When I go to the site, it initially displays all records (correct), but the check boxes don't do anything if I uncheck any of them without any other filter
