### ISSUE TITLE
Change display of Title so that it comes from Item.Item_Specific_Title in all existing cases

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#153]
Currently the Title is displayed from item.edition.title.Title but we need to change all cases of this (e.g., what appears in the results column under "Title"; what appears in the "Collection Contains" and "In Collection" and "Also Appears in" fields; everywhere the title appears) so that what is displayed is the Item_Specific_Title, located at the Item level.

The item.edition.title.Title will be used in future for the new "Work View" we will implement in Issue #29

**Comment by ZacharyLesser** [comment]
Initial state upon coming to the website should be to display all records.

Then the checkboxes should function just as the radio buttons do. 

Even if no filter is done (e.g. nothing is put in the Title field to start), they should update the results.

**Comment by apjanco** [comment]
issue of bold of title after expand
