### ISSUE TITLE
Some data does not show up in Author (Title Page) list of filter choices

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#157]
The following objects appear in the data field "Title Page Author filter" (at Item level) but they do not appear in the drop-down list of filter choices for some reason.

A., R.
C., E.
Alabastro, Gulielmo
Aleman, Mateo
Anglo-Britanno, F.
Armin, Robert
B., H.

...

and many more. 

The associated plays DO appear in results for Author (Title Page) = Any , and the data is there in the field.

Something is preventing these specific entries from being found in the part of Build that creates the filter choices.

**Comment by ZacharyLesser** [comment]
Still not working: check out DEEP 1212 as an example.

At Item level: neither of the terms in Title Page: Author Filter is showing up in the drop-down filter for Author (Title Page). See the data in screen shot. Both of those terms should appear in the drop-down

<img width="1033" alt="Screenshot 2023-10-20 at 9 59 48 AM" src="https://github.com/upenndigitalscholarship/deep/assets/40445411/08ce63c7-a042-4a5f-9d39-a6de2d68e6e6">

**Comment by ZacharyLesser** [comment]
Looking at some other errors on this: see DEEP 5041, which gets hit by a filter on Author (Title Page) = Beling, Richard, but should *not*.

I *think* what is happening is that this filter is filtering on the wrong db field. It should filter on Title Page: Author Filter at the Item level, and it should generate the drop-down list from that field. (I think it is incorrectly working on Authors or Author Filter at the Edition level, which is for Author (Modern))

**Comment by apjanco** [comment]
Now building `title_page_author_filter.json` from `item.title_page_author_filter`
Changed item data from item.edition.authors.all() to item.title_page_author_filter

**Comment by ZacharyLesser** [comment]
Has this build completed? I'm still not seeing the right list of filters, and some of the ones currently on there return no results even when they should.

DEEP 5042

![Screenshot_2023-11-07-16-47-49-42_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/upenndigitalscholarship/deep/assets/40445411/47f547ba-f8ba-4cbe-b34a-60c81059af88)

A, W in author (Title page) returns no hits and B, R is not present in list of filter terms...

**Comment by apjanco** [comment]
Note: needed to trim whitespace `"B., R.; Sidney, Philip; A., W.".split(';').map(s => s.trim());`

**Comment by ZacharyLesser** [comment]
![Screenshot_2023-11-07-18-00-41-13_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/upenndigitalscholarship/deep/assets/40445411/7f50fa88-1656-4125-88ac-dfd449e4a887)

Why is B, R still not appearing in the drop down list of filter terms, but if I enter it into the drop down, it does appear and does function? Filter list needs to be rebuilt?

**Comment by ZacharyLesser** [comment]
Oh I see the problem now, the alphabetical list starts over again about halfway down. So they just need to be sorted properly and I think this is done
