### ISSUE TITLE
Paratextual Material = None count is way too low

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#172]
New DEEP = 392 results
Old DEEP = 609 results

Since "Any" and "None" are derived programmatically from whether data appears in any or none of a group of fields, this is probably an error in the code.

**Comment by ZacharyLesser** [comment]
If you look at Greg 4a, DEEP 4, you will see that there is no data in any of the Paratexts fields (at Item level) -- why is this item not appearing when filtering for Paratexts = None?   Same is true for DEEP 11, Greg 10a. 

Is the filter for Colophon perhaps also filtering on Stationer: Colophon? Or some other field that it should not?

**Comment by apjanco** [comment]
filter is:
```
let paratextual = item => (
            item.paratext_dedication == "" &&
            item.paratext_commendatory_verses == "" && 
            item.paratext_to_the_reader == "" && 
            item.paratext_argument == "" && 
            item.paratext_actor_list == "" && 
            item.paratext_charachter_list == "" && 
            item.paratext_explicit == "" &&
            item.paratext_errata == "" &&
            item.paratext_other_paratexts == ""
            )
```
DEEP 4 is
```json
'paratext_author': None,
 'paratext_explicit': None,
 'paratext_errata': None,
 'paratext_commendatory_verses': None,
 'paratext_to_the_reader': None,
 'paratext_dedication': None,
 'paratext_argument': None,
 'paratext_actor_list': None,
 'paratext_charachter_list': None,
 'paratext_other_paratexts': None,
```

**Comment by ZacharyLesser** [comment]
So why is DEEP 4 not showing up in Paratext = None filter results?
Here's what I see in admin for that Item -- nothing in those fields. What am I missing? Are you seeing "None" (i.e., the word None) appearing in those fields? Is there a difference between "" and None? Given the filter, shouldn't DEEP 4 be hit by that filter?

<img width="1111" alt="Screenshot 2023-08-28 at 3 33 44 PM" src="https://github.com/upenndigitalscholarship/deep/assets/40445411/bc378a23-61d1-45b5-8305-598178677743">

**Comment by apjanco** [comment]
None is not the same as "" That's what I'm working to change.
