### ISSUE TITLE
Theater (Title Page) not working properly

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#173]
This search was not working properly, and I realized that the "Theater Type" field is obsolete anyway. I added "Indoor Professional" and "Outdoor Professional" to the "Theater" field as filter choices. So the entire filter can now work simply on "Theater" (at Item level).

Here's what we need to do:

1) Delete the "Theater Type" field from the db

2) Filter on "Theater" field (at Item level). If ANY data is present in that field = Any; if NO data is present in that field = None

3) Retain the existing layout of the drop-down of filter choices, with Any, None; blank line; Indoor Professional, Outdoor Professional, before the Court, at University; blank line; [alphabetical listing of theater names]

**Comment by ZacharyLesser** [comment]
The filter was working for all the choices EXCEPT None previously, but as I tried to fix this (by deleting "None" from Theater Type if there was data in Theater), I think I somehow broke the Build.py script, because now this filter doesn't work for any of the individual terms that are in the Theater field.

**Comment by ZacharyLesser** [comment]
Ideal solution to all of this:

  1) Wherever "Indoor" or "Outdoor" appear in "Theater Type", copy that data into the "Theater" field. **Do not** copy "None".
  
  2) Delete the field "Theater Type" from the database

  2) Change the filter "Theater (Title Page)" so that it simply searches on the "Theater" field. The filters for "Indoor Professional" and "Outdoor Professional" should hit the data "Indoor" and "Outdoor" respectively. If there is any data at all in the field, "Any" filters on that record; if there is no data in the field, "None" filters on that record

**Comment by ZacharyLesser** [comment]
Build appears to be broken for this filter. It does not rebuild the drop-down choices, and the theaters result in zero hits.

**Comment by ZacharyLesser** [comment]
Filter on "None" returns results that are "before the Court" and "at University" -- these should not be included.

"None" = no data at all present in "Theater" (at Item level)

**Comment by apjanco** [comment]
Let's look at this when we talk.  When Theater (Title Page) is set to "None" the filter is
item.theater equals "None" OR  item.theater_type equals "None"

**Comment by ZacharyLesser** [comment]
Theater type field should be obsolete now because I moved all that data into Theater. I think this is the problem because with that field still involved in the filter, there will be some false positives. Cutting that from the filter may solve the problem immediately

**Comment by ZacharyLesser** [comment]
ie change to

When Theater (Title Page) is set to "None" the filter is
item.theater equals "None"

(but as usual, "None" here just means no data present, not the term "None")
