### ISSUE TITLE
Adjust column widths in results

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#177]
We don't need as much width for DEEP # or Year, and this can let us increase the width of Author and Title. Author in particular needs more width because it frequently runs over onto second or third line. This is inevitable sometimes but can be reduced by increasing the width some.

**Comment by apjanco** [comment]
Try changing values here; https://github.com/upenndigitalscholarship/deep/blob/97bb4a7fb076eb518c96445a9c93228257eddd0c/main/templates/index.html#L95C9-L102C14
