### ISSUE TITLE
Brit Drama # , DEEP #, and other number fields should *not* work by string

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#178]
Right now if you type 707 in the filter, you will get 1707 as a result. This will confuse users

**Comment by apjanco** [comment]
Ready for review

**Comment by ZacharyLesser** [comment]
Almost ready to close. The only problem here is with Greg #. It is correctly now *not* working by string. But in order for it to work properly on the user side, it needs to filter simultaneously on the following fields:

Greg (Brief) -- at the Titles level
Greg (middle) -- at the Edition Level
Greg # -- at the Item level

Filtering on all three fields at the same time (without string searching) will result in the functionality we want.

**Comment by apjanco** [comment]
Added condition to search on greg, greg_middle or greg_full depending on selected level

**Comment by ZacharyLesser** [comment]
Still not working quite right. A search for Greg = 15a returns no hits. Greg = 15 is the right results but it must not be filtering on all 3 Greg fields simultaneously.

The user might just enter 15 but might also enter 15a or 15a(i) and we've accounted for all this by having the three different Greg fields

**Comment by apjanco** [comment]
Note: Title isn't returning all matches because we're only displaying the one record with the lowest DEEP#. That can be fixed in the new Title view. This only applies to greg search. Edition and Record should be working as expected (no result for 2, but result for 2a)

**Comment by ZacharyLesser** [comment]
Let's discuss this on Thursday
The filter shouldn't depend on the View.

**Comment by apjanco** [comment]
Have a look now. A search for Greg Number = 15 returns 4 results. You can also search 15a and get one result.
