### ISSUE TITLE
Layout of Record Display (both expanded view and individual pages)

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#180]
Currently the layout of the record display is not working properly. The design is fine (font, capitalization, etc.). But some fields are not appearing and others are appearing when they should not appear. 

I've noted in RED those fields that should not appear at all if there is no data present in the relevant field in the database.

In GREEN I've highlighted the fields that are currently having problems. These problems are:

Fields that do not show up at all: Genre (Annals); Company of First Performance (Annals); Company Attribution (Title Page); Black Letter; Explicit; Colophon

STC/Wing needs the # like the other numerical fields

Performance and Imprint should appear even if there is no data present (currently they do not appear if no data present)

In Paratextual Material, instead of "Other", it should say "Other Paratexts"

Imprint Location should not appear if no data is present (it currently is displaying "None" in this case)

Entries in the Stationers' Register should say "None" when field is empty

[Layout of Record .pdf](https://github.com/upenndigitalscholarship/deep/files/10992074/Layout.of.Record.pdf)

**Comment by ZacharyLesser** [comment]
Once this is all correct, it needs to be copied so that the individual pages display identically

**Comment by ZacharyLesser** [comment]
There are still some problems here -- compare the layout PDF to some sample records:

Genre (Annals) is still not showing up 
Company of First Performance (Annals) is still not showing up
Company Attribution (Title Page) is still not showing up

Explicit seems to be posing problems (see attached screenshot -- "None" should not appear if there is an Explicit)

Imprint Location not working properly: if no data is present, the line should not appear (currently displaying "None")

Entries in Stationers' Registers: [should always appear -- but if no date present, it should display the word "None", which is not currently happening]

"Date of First Publication" should be on same line as "Date of First Production (Annals)" -- this creates the aligned left and right columns (once you insert Genre (Annals) in the proper place)

There are also too many blank lines before and after "Total Editions," "Variants," "Also Appears in Collection," "Collection Contains," "In Collection," "Also Appears as a Bibliographically Independent Playbook in" -- only one blank line is needed and the blank line is only needed if it is separating items that actually appear. I think the solution is to make the blank line part of what does / does not appear depending on whether there is data in these fields.

<img width="373" alt="Screenshot 2023-10-12 at 3 43 22 PM" src="https://github.com/upenndigitalscholarship/deep/assets/40445411/d92960b0-7af8-4672-8569-5357cda3c49f">

**Comment by ZacharyLesser** [comment]
Still to do on this:

Some problems with spacing: above Additional Notes, and padding at the bottom of each section

In Title-Page Features: Author, Performance, Imprint should always appear, even if no data in the field. They should not display "None" or anything else, if no data in the field.

In Stationer Information: something has gone wrong. The only field that should always appear in "Entries in the Stationers' Registers". The other fields should not appear if they have no data. Currently the word "None" is appearing in odd places because of these other fields, I think.

<img width="350" alt="Screenshot 2023-10-19 at 12 53 31 PM" src="https://github.com/upenndigitalscholarship/deep/assets/40445411/134d6ae2-3284-4137-916c-5664ea94d7eb">

**Comment by apjanco** [comment]
add new class 
```css 
.hanging {
    margin-left: 20px;
    text-indent: -20px;
}```
