### ISSUE TITLE
Set permissions after build

### ISSUE THREAD

**Issue by apjanco** [upenndigitalscholarship/deep#182]
There are times when files are written without www-data:www-data. The build script should adjust permissions on all files to be sure they belong to www-data.  Without this, the admin-side build can fail.

**Comment by ZacharyLesser** [comment]
Has this been completed?

**Comment by apjanco** [comment]
Still an issue when running build. logs show `PermissionError: [Errno 13] Permission denied: '/var/www/assets/jazzmin/css/main.css'` This is likely why the Build complete message doesn't show in admin even though the build finishes.

**Comment by ZacharyLesser** [comment]
"Build complete" now appearing for me, fyi.
