### ISSUE TITLE
"Composition Date" field should not appear at Item level in Admin

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#183]
The "Composition Date" field should appear at Title level only. Currently it is duplicated at Item level as well. Check that all data is identical between each Item and its corresponding Title, and then delete the field at Item level.

**Comment by ZacharyLesser** [comment]
Compare:

item_composition_date

and

title_Date of First Performance (Annals): Display

**Comment by apjanco** [comment]
remove item.composition_date

**Comment by ZacharyLesser** [comment]
Just reopening this for now, you can send it for Review once you've actually deleted it and I'll close it.
