### ISSUE TITLE
Why does a filter on Title = "comedies," not hit Shakespeare, Comedies, Histories, and Tragedies?

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#184]
If you start filtering on Title and you type "comedies" , you will see a list of the correct results.

If you then type a comma after "comedies" -- you will see most of the results disappear, including "Comedies, Histories, and Tragedies" which *should* still appear.

I can't figure out why this would happen when the filter *does* still hit "Comedies, Tragicomedies, and Tragedies" and "Comedies, Tragicomedies, With other Poems" which both begin with exactly the same character string through the comma.

**Comment by apjanco** [comment]
Search fields are punctuation insensitive. Any comma, period, colon, semi-colon, question mark, hyphen, or underscore is removed from the query. I don't remember why we added that, but it was requested. I can remove it if you don't want it.

**Comment by ZacharyLesser** [comment]
This doesn't explain it, though, because filtering on Title for

comedies histories

still does not hit the record. And including the comma does not pose the same problem for "Comedies, Tragicomedies, With Other Poems"

So something else is wrong here.

**Comment by apjanco** [comment]
We were replacing punctuation with a space.  Now I've made it so that it just removes it. That may help with this issue.

**Comment by ZacharyLesser** [comment]
Yes! that has fixed it.
