### ISSUE TITLE
Individual record display does not yet match completely

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#188]
Still not identical -- they need to match 100%

**Comment by ZacharyLesser** [comment]
I closed #151 -- adding spaces after the colon of some fields in individual records display -- because it will be dealt with by this. Also differing are the display of certain fields, which are working properly in the full display of results but are not in the individual record (i.e., which ones always display, and which ones display only when data is present)...

**Comment by apjanco** [comment]
Item page should be the same as the search page

**Comment by ZacharyLesser** [comment]
Not quite working. When you click a link for a variant, the page opens and has the correct URL but does not display the record. When I do this for Collection Contains links, it does display the record.

**Comment by ZacharyLesser** [comment]
Update: they seem to work on chrome but not on Firefox
