### ISSUE TITLE
STC # and BritDrama # need to search multiple numbers independently

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#204]
In each of these fields, there are 4 items that have multiple numbers in the field, separate by semicolons.

When a user searches for one of these numbers, it should return the record. Right now they have to enter both, with the semicolon, for the record to be hit. It should treat each number as a discrete number and either one of them will suffice to hit the record.

**Comment by ZacharyLesser** [comment]
When there is more than one number in these fields, they should appear in Display as follows, if possible:

1) lowest number first
2) alphabetically for those with a letter at the start
3) numbers before any with a letter at the start.

**Comment by ZacharyLesser** [comment]
DEEP, Greg, BritDrama, STC/Wing should all search for numerals, so that "25" does not also hit 251, 252, 525 etc

**Comment by ZacharyLesser** [comment]
Some problems resolved, but others created:

I think the problem with string searching has been solved, BUT: now we can no longer hit a record that has 2 STC/Wing or BritDrama #s.

If you search for STC/Wing = 14959 or BritDrama = 1488 or BritDrama = 1489, you get no hits. Because these numbers are all in records with more than one value for those fields. 

Is this impossible to do unless we re-implement string searching here (which causes other problems)? If so, maybe the best way to handle this to add a second STC/Wing and a second BritDrama field and have these filters run on both those fields? (In most cases the second field will be empty)

**Comment by apjanco** [comment]
changed to regex with split on space, working for brit drama but not stc/wing.
also make changes to OR after AND is working
