### ISSUE TITLE
In Work View, what to do with DEEP # and Year

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#214]
These columns don't strictly apply in Work View. It's hard to totally redo the table "live" as the user clicks Work or Edition or Record View. How to handle this?

**Comment by ZacharyLesser** [comment]
Show only editions, not all records, in the list under each Work

**Comment by ZacharyLesser** [comment]
In older issue you wrote: "try to hide year and deep number"

**Comment by apjanco** [comment]
https://github.com/javve/list.js/issues/121
