### ISSUE TITLE
There's an odd band of a different color at bottom of screen

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#225]
Not sure what that blue line is doing there. 

<img width="1281" alt="Screenshot 2024-04-03 at 11 43 14 AM" src="https://github.com/upenndigitalscholarship/deep/assets/40445411/d4c42f25-a605-462d-9ea4-69fb2628243b">

**Comment by apjanco** [comment]
That area is the footer.  It can be removed or populated with logos, links and such.
