### ISSUE TITLE
Add new "Views"

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#29]
The "edition" view is the basic one being implemented. We need to make sure the "Record" view is functioning properly, simply omitting the de-duplicating routines. We still need to implement the "Work" view -- which requires a completely different record display system.

**Comment by ZacharyLesser** [comment]
(Note to self: the Title view will display Work.Title while the Edition and Record views will display Edition.Title)

**Comment by apjanco** [comment]
try to hide year and deep number

**Comment by apjanco** [comment]
switch from greg to work id
