### ISSUE TITLE
format sources.html 

### ISSUE THREAD

**Issue by apjanco** [upenndigitalscholarship/deep#30]

**Comment by ZacharyLesser** [comment]
Still missing html formatting like italics etc -- see old site:

http://deep.sas.upenn.edu/sources.html

**Comment by apjanco** [comment]
This issue is specific to the sources.html template. #18 about formatting in the data is still open.

**Comment by ZacharyLesser** [comment]
Yes, but even in the sources, there is formatting missing, like italics for titles of the sources.

It's no problem for me to do this if the page can be edited from Admin. In the django admin for the Shakespeare Census there's a section for Static Text Pages that allows me to edit them directly without going into the code itself. Is this possible?
