### ISSUE TITLE
Initial sorting of filter results

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#32]
When user filters records, the initial state of results should be sorted:

1) first by Year -- then
2) within the same year, by DEEP ID

**Comment by ZacharyLesser** [comment]
Sorting by Year should sort on "Year INT", NOT on "Year (of publication)" (at the Item level) -- this will solve the problem of dates with brackets in them not sorting properly (as currently)

**Comment by apjanco** [comment]
List.js can call a sort 
`table.sort('year', { order: "desc" });
table.sort('deep_id', { order: "desc"});`
should be what we need

**Comment by apjanco** [comment]
added sort() whenever search() is called. Even though table.update() is called right there, it's not updating the table as expected. Works in console, so seems to be the right call.  I tried adding a coroutine on update, but not good.
