### ISSUE TITLE
Theater (Title-Page Attribution) filter terms not correct

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#34]
When you try to filter on "Theater (Title-Page Attribution)", the list of choices in the drop-down is not correct. Compare to the old site. The list in the drop-down should be ordered as follows.

Any
None

Indoor Professional                  
Outdoor Professional                   
before the Court                           
at University

Blackfriars
Curtain
Fortune
Globe
Paul's
Phoenix/Cockpit
Red Bull
Rutland House
Salisbury Court
St. Werburgh Street, Dublin
Swan
Whitefriars
Whitehall

**Comment by ZacharyLesser** [comment]
The four terms in the second group beginning with "Indoor Professional" are determined by the table, Theater Type -- 
if it says "Both Indoor and Outdoor" then it should be hit by either "Indoor Professional" or "Outdoor Professional".  

The terms in the "Theater Type" field, note, are not themselves shown in the list of filter terms

**Comment by apjanco** [comment]
fixed, outdoor professional == outdoor && both outdoor and indoor. But broke later conditions, need to fix

**Comment by apjanco** [comment]
Actually working fine in dev, check later that update is working as expected in prod.
