### ISSUE TITLE
Blackletter filter not working properly

### ISSUE THREAD

**Issue by abfarmer109** [upenndigitalscholarship/deep#39]
The Blackletter filter should include the following: "Yes" and "No"

This filter returns "Yes" if there is any data at all in the field "Title Page: Blackletter" which is at the Edition level.

If there is no data at all in this field, it is "No".

**Comment by apjanco** [comment]
In the old database, each Deep has a field called blackletter that is either None, 'Yes' or 'Yes, Partly'. That is the only data I have. Can you give me an example of what appears in "Title Page: Blackletter"?
