### ISSUE TITLE
"Blackletter" field not displaying in the results

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#40]
If and only if there is data in the field "Blackletter" (which is at the Edition level), then the data label "Blackletter:" should appear directly beneath "Leaves:" in the record display. 

This should display whatever data is in the Blackletter field (edition level).

**Comment by apjanco** [comment]
The only values in the db for blackletter are {'', 'Yes', 'Yes, Partly'}. The filter has yes and no. If no is selected, it displays records with "". If "yes" selected, it shows "Yes" or "Yes, Partly". The dropdown is showing yes no twice, but is working as expected.

**Comment by ZacharyLesser** [comment]
OK - this issue was only about Display. The filtering problem is addressed in another issue, as you can see.  

For Display, whatever is in the field should display -- if there is nothing in the field, the entire field (including the header) should not appear in the Results Display.

For Filtering, see Issue #39
