### ISSUE TITLE
Author (Title-Page Attribution) filter not working

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#43]
For this filter, place "Any" and "None" at the top of the drop-down, then a blank line, and then an alphabetized list of the names in the field that this filters on.

The field this filters on is not currently in the new database. It goes at the Item level. The data will be in a table from the old site. This field does not display in the results, because the information it refers to is already accounted for in the Title-Page Features - Author section. We need the data table because it is a curated list of controlled names.

**Comment by apjanco** [comment]
title-page-author is currently a search_field that matches on data in title_page_author
current title_page_author should be considered a display value.
Need a new field in models for title_page_author_filter
Data found in olddb and in backup/author_attribution_filter.tsv (write import script).
