### ISSUE TITLE
Company (Title-Page Attribution)

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#47]
This filter should have "Any" and "None" at the top followed by a blank line, followed by an alphabetized list of the terms in the filter terms field. 

Filter terms field should be "Company" at the Item level. BUT: please rename this field "Company Title-Page Attribution: Filter terms"

The field "Company Attribution" is the display field.

There is a problem with the way data in the Company (soon to be "Company Title-Page Attribution: Filter terms" field is handled. Some records will have two terms in this field, because both are filters for the record. Right now they are run together as a string. These need to be handled as separate filter terms. (i.e., exactly the way "Authors" at the Edition level is currently working)

**Comment by apjanco** [comment]
I think I need more information to fix this. I added Any/None. The filter choices are distinct. However, I need help with the  display value. The old site displays the string with ; separations.  Such as:
Company Attribution: Children of the Chapel (first);Children of Paul's (first) 
http://deep.sas.upenn.edu/viewrecord.php?deep_id=111

Should this be removed? I can add separate filter/display fields, but I'm not sure what goes in display.

**Comment by ZacharyLesser** [comment]
We do want to run together the data for Display purposes in this way, separated by a semicolon, but Note: there should be a space after the semicolon and before the next term.

What I can't remember is whether there is a separate Display table for Company Title-Page Attribution in the old db. I think there may not be: it may simply take the Filter terms and display them by putting them together with the semicolon in this way.

**Comment by ZacharyLesser** [comment]
PS I see that on the old site for deep 111, which you linked to, there is NOT a space after the semicolon in this field (though there is in the field Company of First Production). But this is an error in the old site: a space should always be added after a semicolon on the new site.

**Comment by apjanco** [comment]
Ah! Add spaces, that's easy. Thanks!
