### ISSUE TITLE
Play Type filter not working correctly

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#48]
We discussed this at the meeting.

Currently the filter terms in the drop-down are taken from the Display data, not the filter terms data.

The display data is appearing in Play Type, but it is appearing in the form of a Filter Terms field (like "Authors" with the option of multiple items in that field). This field should be renamed Play Type Display and turned into a text string.

A new field Play Type: Filter Terms needs to be added with the data you should hopefully find in a table from the old site that hasn't been used yet.

**Comment by apjanco** [comment]
Some progress here, need to check results against old site
