### ISSUE TITLE
Filters with date ranges -- initial state

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#59]
If the filters with date ranges will populate those ranges automatically with 1512 and 1661, as they currently do, then the initial state of search results should logically be the results of that search. But it is not. The initial state is currently 0 results.

I think it is better if when the filter is selected, the date range boxes show up but they are NOT populated yet with any dates. Then as the user enters dates, the results appear.

**Comment by ZacharyLesser** [comment]
Filters with date ranges should be INCLUSIVE dates. If the end date is 1522, it should include all items with 1522 as their relevant date. Currently, it appears these searches are EXCLUSIVE, and you have to put in 1523 in order to return the records that have 1522 as their relevant date.

**Comment by apjanco** [comment]
No problem to change greater than to  greater than or equal to. I changed the input field to placeholders rather than initial values. This retains the max/min range information and example of what constitutes valid input. Does this address the issue?

**Comment by ZacharyLesser** [comment]
This appears to have been fixed for Year Published but not for the other date range fields?

Note that for Date of First Production, 1512 is *not* the earliest year in the database in that table

Date of First Performance (BritDrama) does not appear to be filtering at all.

Date of First Edition does not work correctly -- searching for end date of 1520 yields only 1 result, but on the old site yields 7. And sometimes it returns no results at all, not sure why. It seems to depend on how you go about inputting the dates, which one you do first or something? Not sure.

**Comment by ZacharyLesser** [comment]
Date of First Performance (BritDrama) filter for 1575 - 1575 returns no results. It *should* return all results with the date 1575 in the  Date of First Performance (BritDrama) field (i.e, the filter field, not the display field). Something still off with the >= and <= formula?
