### ISSUE TITLE
Variant Description not extending across entire page in new-tab / pop-up records

### ISSUE THREAD

**Issue by abfarmer109** [upenndigitalscholarship/deep#65]
When you click on a link in a variant description, a new window that opens for that record. In that new pop-up window, the variant description does not extend across the entire page.

For instance, the variant description in DEEP 734 contains this link: [420a(†)](https://deep.pennds.org/735.html).

When you click on that link, the variant description in DEEP 735 does not extend across the entire page. The same is true also when you click on its link back to DEEP 734.

This issue was fixed earlier for items in the main result template.

**Comment by ZacharyLesser** [comment]
note that the same problem occurs with the field Total Editions.

Same exact fix as before for the main results template.
