### ISSUE TITLE
Choosing/Changing the item record in "Independent playbook link"

### ISSUE THREAD

**Issue by abfarmer109** [upenndigitalscholarship/deep#66]
The item for DEEP 5149.03 contains a link in the field "Independent playbook link."

That link, however, is for the wrong play. It currently is to DEEP 821, but it should be to DEEP 734.

There is a way to change the link, but right now other items in that field appear in a seemingly random order, making it all but impossible to find DEEP 734. It would be best for them to be sorted by "DEEP # -- Play Title," i.e., as they appear now but ordered by DEEP #.

**Comment by ZacharyLesser** [comment]
Shouldn't this be DEEP 817 (Broken Heart)?

**Comment by abfarmer109** [comment]
The links in the following field are wrong for for the plays in this 
collection DEEP 5149.


That is, for each of the records for the "plays in collection," the link 
from back to the bibliographically independent playbook is off, and in 
Firefox, there is no way for me to correct them.

5149.01 -> 736 [but should go to 734]
5149.02 -> 827 [but should go to 823]
5149.03 -> 821 [but should to to 817]
5149.04 -> 819 [but should to go 815]
5149.05 -> 838 [but should go to 833]
5149.06 -> 885 [but should go to 883]
5149.07 -> 915 [but should go to 918]
