### ISSUE TITLE
"Independent playbook link" not updating

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#69]
I tried to fix an error in the db for DEEP 5149.01

The independent playbook link was going to DEEP 736 but should point to DEEP 734.

I changed the data in the field and it did change successfully, so you can see it is now pointing to 734.

But on the site itself, it still pops open a tab with the incorrect item (736). The site does not seem to be updating / pulling the new data properly.

**Comment by apjanco** [comment]
Independent playbook for 5149.01 is showing a link to 734. The live site is only updated when a build is run. This allows versioned updates and a much more stable and sustainable site.
