### ISSUE TITLE
Algorithm for URL by DEEP #

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#75]
Currently the website includes *.html at the end of the URL for each item by DEEP # -- on the old site the .html was not necessary and so other sites that point to DEEP do not include it. 

Correct by allowing URLs of the form: https://deep.pennds.org/5072.02 [DEEP #] to work as well

**Comment by apjanco** [comment]
in progress, still need to adjust relative imports in item pages
