### ISSUE TITLE
Add button in admin to trigger a build 

### ISSUE THREAD

**Issue by apjanco** [upenndigitalscholarship/deep#76]

**Comment by apjanco** [comment]
There is now a link "Build" in admin at the top of the screen. Click on that and it will run a build.  It's showing "502 Bad Gateway" at the moment, but it's actually working.  Need to fix.

**Comment by ZacharyLesser** [comment]
I edited the /whats_new page from the Flat Page section of admin -- to remove the header (DEEP: Database...) and the footer (contact, how to cite), both no longer needed there. I ran the Build and got the 502 error but the site did not actually update. What am I doing wrong?

**Comment by ZacharyLesser** [comment]
I also tried fixing a typo in the data in Greg 98a -- which mistakenly had "98(a)" in that field. So I removed the parentheses and ran a Build but the change does not actually show up on the site.

So I am thinking the Build button is working maybe only on your end but not, for some reason, on mine? 

Or does it take some time even after running the Build for it to show up on the site?

**Comment by ZacharyLesser** [comment]
Even weirder update! 

If you go directly to https://deep.pennds.org/132/ -- the change has been made.

But if you go to the main page and search for the record (e.g, Title = Elvetham), then the change is not made and 98(a) still appears. Strange!

**Comment by ZacharyLesser** [comment]
Ok both of these now appear correctly on my phone. So either there is a slight delay or there is a problem with my computer caching the page and not registering the changes

**Comment by apjanco** [comment]
Added improved UI, shows "Build", "Running Build" and "Build Complete" Had server-side problem, fixed with proxy timeout in nginx and gunicorn https://www.datadoghq.com/blog/nginx-502-bad-gateway-errors-gunicorn/#gunicorn-is-timing-out
