### ISSUE TITLE
What is deep.transcript_engraved_frontispiece?

### ISSUE THREAD

**Issue by apjanco** [upenndigitalscholarship/deep#82]
I'm migrating the fields with formatting from the old database. There is a field called transcript_engraved_frontispiece in the data, but it does not seem to appear on the site. What is it?

['1182   This edition is not in Greg.',
 '898   Engraved portrait inscribed "Vera effigies. Abrahami Cowley. regii alumni scholæ West:" and "Ætatis Suæ 13" [A1v]',
 '953   [A1v] Engraved portrait inscribed "Vera, ac viva Effigies Nathanaelis Richards Gen:" with motto and coat of arms, signed signed "TR sculp:" [A1v]',
 '1005   Engraved portrait inscribed "Bapt: Guarini the author of Pastor fido æt: suæ LXIII" with arms below and couplet in English, signed "T: Cross sculpt:" [A1v]',
 '1006   Engraved portrait inscribed "Bapt: Guarini the author of Pastor fido æt: suæ LXIII" with arms below and couplet in English, signed "T: Cross sculpt:" [A1v]',
 '1035   Engraved portrait of Prince Charles (later King Charles II) with  view inscribed "Iersey" (where Charles was in 1649) and below “Ætatis suæ.19." [π1v]. Engraved portrait of  Princess Elizabeth (second daughter of King Charles I) with four lines of verse below [π2r] ',
 '1044   Engraved frontispiece inscribed with verses [π1v] (a folding leaf)',
 '1052   Engraved portrait (with six lines of verse below subscribed "Leo: Willan ipse Scripsit") signed "T. Cross sculpsit" [A1v] ',
 '1064   Engraved portrait inscribed "Effigies Hugon. Grotij"  and signed "Cross fecit" [π1v]. Engraved portrait of translator subscribed with four lines of verse and signed "T. Cross fecit" [B3+1v].',
 '5167   Engraved frontispiece signed "p stent exc:" [A1v]',
 '5168   Engraved frontispiece signed "p stent exc:" [A1v]',
 '1176   Engraved portrait (unsigned) surmounted by a coat of arms with the motto "Amico rosa inimico spina" [A1v] ',
 '1193   Engraved portrait with "Ignoramus" on scroll held by figure [A1v].',
 '1195   Engraved portrait with "Ignoramus" on scroll held by figure [A1v].',
 '1196   Engraved portrait (rougher copy) with "Ignoramus" on scroll held by figure [*1v].',
 '1197   Engraved portrait (rougher copy) with "Ignoramus" on scroll held by figure [*1v].',
 '1198   Engravings of "Dromodotus" [A1v] and of "Pedantius" [A2r].',
 '5062   Engraved portrait inscribed "S W.A. Aut. Spero Aut. Sperno. 1616." [A1+1v]',
 '5106   Engraved portrait inscribed "Vera effigies Gulielmi Comitis de Sterlin. Ætats suæ LVII." and signed "Wilhel: Marshall. sculpsit" [A1+1v]',
 '5076   Engraved portrait inscribed "Vera effigies doctissimi poetarum Anglorum Ben: Iohnsonii" and signed "Ro: Vaughan fecit" with verses in Latin and English signed "Ab: Holl." [A1v]',
 '5133   Engraved portrait inscribed "Ioannis Miltoni Angli Effigies Anno Ætatis ViGes: Pri:" with verses below and signed "W. M. sculp:" [a1+1v]',
 '5134   Engraved portrait with verses below and signed "W. Marshall sculpsit. 1646" [A1+1r]',
 '5135   Engraved portrait inscribed "Obijt anno Ætatis suæ 28." with verses (unsigned) on "Sucklin" below and signed "W. Marshall fecit" [<sup>π</sup>A1+1v]',
 '5136   Engraved portrait inscribed "Obijt anno Ætatis suæ 28." with verses (unsigned) on "Sucklin" below and signed "W. Marshall fecit" [<sup>π</sup>A1+1v]',
 '5137   Engraved portrait inscribed "Obijt anno Ætatis suæ 28." with verses (unsigned) on "Sucklin" below and signed "W. Marshall fecit" [<sup>π</sup>A1+1v]',
 '5141   Engraved portrait inscribed "Ætat: Suæ 17" and signed "W. Marshall sculpsit" with below a Latin couplet signed "John Hobart Gent:" [π1v]',
 '5143   Engraved portrait, with coat of arms above and Latin verses signed "J. Berkenhead" below, inscribed "Poetarum ingeniosissimus Ioannes Fletcherus Anglus, Episcopi Lond: Fili Obijt 1625 Ætat: 49." and signed "Guliel Marshall Fecit" [π1v].',
 '5159   Engraved portrait inscribed "Thomas Stanley Arm:" and signed "P: Lilly pinxit. Guil: Faithorne scul" [1+π1v]',
 '5160   Engraved portrait inscribed "Thomas Stanley Arm:" and signed "P: Lilly pinxit. Guil: Faithorne scul" [1+π1v]',
 '5138   Engraved portrait inscribed "Obijt anno Ætatis suæ 28." with verses (unsigned) on "Sucklin" below and signed "W. Marshall fecit" [<sup>π</sup>A1v]',
 '5142   Engraved portrait inscribed "Ætat: Suæ 17" and signed "W. Marshall sculpsit" with below a Latin couplet signed "John Hobart Gent:" [π1v]',
 '5146   Engraved portrait signed "P Lombart, sculp. A. london," inscribed "Obijt Anno 1643" and with verses below [π1v].',
 '5153   Engraved portrait, with verses signed "A. B." below, signed "T. Cross Sculpsit" [π1v].',
 '5155   Engraved portrait with verses below and signed "W. Marshall sculpsit. 1646" [π1+1v]',
 '5165   Engraved portrait inscribed "Vera ac Viva Effigies Philippi Massinger. Geñ" and signed "T. Cross fecit" [π1v]',
 '5154   Engraved portrait, with verses signed "A. B." below, signed "T. Cross Sculpsit" [π1v].',
 '5171   Engraved portrait inscribed "Vera Effigies Tho: Midletoni Gent:" (unsigned) [π1v]',
 '5173   Engraved portrait (unsigned) with verses on "Cockains Head" (unsigned) below [A1+1v].',
 '5174   Engraved portrait (unsigned) with verses on "Cockains Head" (unsigned) below [A1+1v].',
 '5180   Engraved portrait inscribed "Iacobus Shirlæus:" subscribed "G Phenik pinx:" "R. Gaywood fecit 1658" [A1+1v]',
 '5139   Engraved portrait inscribed "Obijt anno Ætatis suæ 28." with verses (unsigned) on "Sucklin" below and signed "W. Marshall fecit" [π1v]',
 '5175   Engraved portrait (unsigned) with verses on "Cockains Head" (unsigned) below [A1+1v].',
 '5181   Engraved portrait inscribed "Iacobus Shirlæus:" subscribed "G Phenik pinx:" "R. Gaywood fecit 1658" [A1+1v]',
 '1194   Engraved portrait with "Ignoramus" on scroll held by figure [A1v].',
 '5156   Engraved portrait with verses below and signed "W. Marshall sculpsit. 1646" [π1+1v]',
 '5140   Engraved portrait inscribed "Obijt anno Ætatis suæ 28." with verses (unsigned) on "Sucklin" below and signed "W. Marshall fecit" [π1v]']

**Comment by ZacharyLesser** [comment]
This data should be preserved -- it was a field that we never implemented, I think, but that ultimately probably belongs as one of the Paratexts in filter searching and in display.
