### ISSUE TITLE
Change filter names: "Author (Modern Attribution)" to "Author (Modern)" and "Author (Title-Page Attribution)" to "Author (Title Page)" (nb no hyphen)

### ISSUE THREAD

**Issue by ZacharyLesser** [upenndigitalscholarship/deep#99]
Just changing the wording of the filter on the user side for the following:

"Author (Modern Attribution)" to "Author (Modern)" 
"Author (Title-Page Attribution)" to "Author (Title Page)" (nb no hyphen)
Authorial Status (Title-Page Attribution) to "Authorial Status (Title Page)"
Company  (Title-Page Attribution) to "Company (Title Page)"
Theater  (Title-Page Attribution) to "Theater (Title Page)"
Genre (Title-Page Attribution) to "Genre (Title Page)"

**Comment by apjanco** [comment]
There are two main types of option blocks AND or OR.  Both are created by deep.js.  They're basically the same, but OR blocks have two input areas.      

You can adjust the AND block [here] (https://github.com/upenndigitalscholarship/deep/blob/fbef5d80b8c45c09ce77a01fefca04ea4e10c5b3/main/assets/js/deep.js#L545)

The OR block is created [here](https://github.com/upenndigitalscholarship/deep/blob/fbef5d80b8c45c09ce77a01fefca04ea4e10c5b3/main/assets/js/deep.js#L673)
